name: Tests

on: [push,workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
      - uses: microsoft/playwright-github-action@v1
      - run: |
          cd e2e-tests/
          npm install
          
          cd test_wrk/
          nim -b:cpp r --gc:arc -d:danger --threads:on -d:threadsafe -p:../../src/ test_wrk
          cd ..
          
          cd test_ctxheader/
          nim c -r --gc:arc --threads:on --d:threadsafe -p:../../src/ server.nim &
          sleep 5
          cd ..
          npm run test_ctxheader
          
          cd test_ctxws/
          nim c -r --gc:arc --threads:on --d:threadsafe -p:../../src/ server.nim &
          sleep 5
          cd ..
          npm run test_ctxws     
          
          cd err_empty_response/
          nim c -r --threads:on --d:threadsafe -p:../../src/ server.nim &
          sleep 5
          cd ..          
          npm run err_empty_response
          kill -INT $!
